name: task_orange_bay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  injectable: ^2.5.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  easy_localization: ^3.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  easy_stars: ^1.0.9
  flutter_animate: ^4.5.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_serializable: ^6.6.2
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/translations/
    - assets/lottie/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
